server:
  port: 8085

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3356/auth_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      enabled: false
    import-check:
      enabled: false

jwt:
  secret: sa4u0SjY2lQv2NGsD61y5Qfe304fURqfbRqkD4lke5w=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info