global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'yoga-class-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8083', 'host.docker.internal:8089']