server:
  port: 8084

spring:
  application:
    name: instructor-service
  datasource:
    url: jdbc:mysql://localhost:3356/instructor_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info