server:
  port: 8082

spring:
  application:
    name: studio-service

  web:
    resources:
      static-locations: file:uploads/

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3356/studio_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

file:
  upload-dir: uploads

management:
  endpoints:
    web:
      exposure:
        include: health,info